name: Check House UNH Disclosures

on:
  schedule:
    - cron: '0 13 * * *'  # 09:00 ET daily
  workflow_dispatch:

jobs:
  run-house-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr poppler-utils
        pip install pdfplumber pytesseract pdf2image requests beautifulsoup4 python-pushover

    - name: Run House Disclosure Script
      env:
        PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      run: |
        python scripts/check_house_disclosures.py
