name: Senate UNH Disclosure Check

on:
  schedule:
    - cron: "0 13,16,20 * * *"  # 09:00, 12:00, 16:00 ET
  workflow_dispatch:

jobs:
  run-senate-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr

      - name: Install Python & Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install chromium

      - name: Run Senate UNH Disclosure Parser
        env:
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        run: python scripts/parse_unh_disclosures.py