name: Senate UNH Disclosure Check

on:
  schedule:
    - cron: '0 13 * * 1'  # Every Monday at 09:00 ET (13:00 UTC)
  workflow_dispatch:

jobs:
  check_senate_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils tesseract-ocr
          pip install -r requirements.txt

      - name: Run Senate ZIP parser
        env:
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
        run: python scripts/parse_unh_disclosures.py
