name: UNH Disclosure Alert

on:
  schedule:
    - cron: "0 13,16,20 * * *"  # Run at 9am, 12pm, 4pm ET
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright CLI
        run: pip install playwright

      - name: Install Playwright Browsers
        run: playwright install chromium

      - name: Run UNH disclosure parser
        run: python scripts/parse_unh_disclosures.py
