name: UNH Disclosure Monitor

on:
  schedule:
    # Runs at 9:00 AM, 12:00 PM, and 4:00 PM ET (convert to UTC)
    - cron: '0 13 * * 1-5'   # 9:00 AM ET = 13:00 UTC
    - cron: '0 16 * * 1-5'   # 12:00 PM ET = 16:00 UTC
    - cron: '0 20 * * 1-5'   # 4:00 PM ET = 20:00 UTC
  workflow_dispatch:        # allows manual trigger

jobs:
  run-unh-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UNH disclosure parser
        env:
          GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        run: python scripts/parse_unh_disclosures.py