name: UNH Senate Scraper

on:
  schedule:
    - cron: '0 13,16,20 * * *'  # 3x/day UTC
  workflow_dispatch:
  push:
    paths:
      - 'scripts/**'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests

      - name: Install Playwright browser
        run: playwright install chromium

      - name: Run UNH disclosure parser
        run: python scripts/parse_unh_disclosures.py
        env:
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}